-- 2026-09-13: bounded collection evidence for failed N30 jobs (30-day retention).
-- The local worker summarises every capture of a failed collection (identities and
-- raw numbers only, no titles or prices, <= 16 KB) and the server stores it here so a
-- production failure can be diagnosed from data instead of inferred from its code.
begin;
create table if not exists public.naver_shopping_failure_evidence (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  worker_id text not null,
  run_id uuid,
  runtime_version text,
  tracker_id uuid,
  keyword text not null,
  error_code text not null,
  scope text not null,
  evidence jsonb not null,
  retention_until timestamptz not null default (now() + interval '30 days'),
  constraint naver_shopping_failure_evidence_size check (pg_column_size(evidence) <= 32768)
);
create index if not exists idx_naver_shopping_failure_evidence_time
  on public.naver_shopping_failure_evidence (occurred_at desc);
create index if not exists idx_naver_shopping_failure_evidence_tracker
  on public.naver_shopping_failure_evidence (tracker_id, occurred_at desc);
create index if not exists idx_naver_shopping_failure_evidence_retention
  on public.naver_shopping_failure_evidence (retention_until);
alter table public.naver_shopping_failure_evidence enable row level security;
revoke all on table public.naver_shopping_failure_evidence from public, anon, authenticated;
grant select, insert, delete on table public.naver_shopping_failure_evidence to service_role;
commit;
